### PR TITLE
Add fast drop option, use default encoding

### PR DESCRIPTION
**Pull request by NotAFile**
also one whitespace fix because I couldn't resist

I hadn't seen you had actually kinda merged the previous commits from us, you might want to close the relevant issues and PRs :+1: 

(#5, #6 and #7 can all be closed)

### CODE REVIEW

**Comment by noway** [comment]
LGTM 👍

**Comment by LinuxDonald** [comment]
@aresch any news about this pr?

**Comment by NotAFile** [comment]
doubt it

**Comment by aresch** [comment]
Sorry, I lost track of this (life has been busy).

**Pull request merged**
